### ISSUE TITLE
batti is broken with new update

### ISSUE THREAD

**Issue by zerOnepal** [foss-np/batti#20]
$ batti -u  is broken. 
Reason :: They really cumbersome the new pattern. 3 times a day. Really not good. Some universal soultuions should be re-thouht.
![screenshot70](https://f.cloud.github.com/assets/1695906/1753143/ea2804d6-6635-11e3-8941-9db07eef6ce8.png)

**Comment by munikarmanish** [comment]
I think NEA should provide the data in a parsable format as well. Shouldn't be that hard for them either. Can we request that?

**Comment by rhoit** [comment]
@munikarmanish I don't know give it a try! any ways where is fun in extracting parsable data ;) For now it can't parse the 3 row data..  try if you can solve this problem when it happens! (I guess its coming soon)

**Comment by munikarmanish** [comment]
Parsing "unknown" number of load-shedding per day just with the help of the traditional PDF file is going to be over-complicated and totally against the KISS philosophy. :)

**Comment by zerOnepal** [comment]
again, we have 3 in a row problem, goooooooood, may the force be with us

**Comment by rhoit** [comment]
done with temp fix! thanks @zerOnepal for getting it started! but kinda day wasted.
