### ISSUE TITLE
Extract Effective Date of Implementation

### ISSUE THREAD

**Issue by nootanghimire** [foss-np/batti#30]
Can we extract the effective date of implementation and display schedule according to that.

Suppose I generally automatically update batti in fixed interval: Nea publishes new schedule before it is implemented. If I happen to update the app in that time, I would get new schedule, which is not what user wants.

**Comment by rhoit** [comment]
We will love to have the pull-request, but for now it just works.

**Comment by rhoit** [comment]
@nootanghimire I'm not in mood to fix this issue, and seem like other aren't much excited after all, it has been 10 months *SIGHT*, closing this Issue, pull request is always welcomed.
