### ISSUE TITLE
batti displaying old routine

### ISSUE THREAD

**Issue by samundra** [foss-np/batti#32]
I tried updating the loadshedding routine using 

```bash
$ batti -u
```
and it displays the old routine. I tried to clear every temporary file that batti creates even after that it is displaying the old routine. We should an option to **force update** routine.

I looked at the downloaded **nea.pdf** file and it is indeed the latest one. Perhaps the routine is being loaded from somewhere else.

**Old Routine**
![Old Routine](http://i76.photobucket.com/albums/j5/alexshr/batti-u_stopped_working_zpskf1kvo51.png)

**New Routine**
- should have been the **nea.pdf** downloaded from NEA site.

**Comment by rhoit** [comment]
@samundra actually routine is correct, but it takes extra one row! by mistake.. KINDA NEW THIS THINGI.. too lazy write the new logic for correction just edit the stuff.
