### ISSUE TITLE
Too many stuffs in readme, move to wiki instead

### ISSUE THREAD

**Issue by samundra** [foss-np/batti#33]
#### Suggestion

There are just too many instructions in the Readme and it confuses the general user. How about cleaning it up and keeping only installation part in the Readme? We can move rest of the parts to Wiki. 

What do you guys think about it? @rhoit @krazedkrish @zerOnepal @hardfire @munikarmanish

**Comment by rhoit** [comment]
@samundra may be! I don't have pretty good perspective since I don't look though the eye of the user.

**Comment by samundra** [comment]
The readme document is very thorough for developers but for someone who is willing to give it a try it's confusing. May I refactor the readme for ubuntu users?

**Comment by rhoit** [comment]
ya we could write the wiki, but there is not much of content for the wiki pages, you are always welcomed to create one.

**Comment by rhoit** [comment]
ya we could write the wiki, but there is not much of content for the wiki pages, you are always welcomed to create one.

**Comment by samundra** [comment]
I will try to restructure the readme someday. Lets keep this issue open.

**Comment by hardfire** [comment]
Awesome, looking forward to the changes and I'll try to build and run it once to get a user perspective to it ! 

Regards,
Avinash

**Comment by krazedkrish** [comment]
I think the current read me is not bad. If wiki is to be added, i dont know how it can be good.
My analysis is the following topics

Setting up
Dependencies
Install
-Arch
-Ubuntu
-Building deb
-Manual
HOW-TO USE

are required in Readme.
Except these there is only a few to be removed.

Since, the content is so little, i believe, either we should wait for the readme to increase, or we should add more contents in wiki to separate articles from read me and wiki.

**Comment by samundra** [comment]
In my opinion the current readme has enough informations for developers. We
have to make it such that it can be easily installed by newbie too. That's
what I am intending by proposing to moving contents to wiki on their own
topics.
e.g.
1) Installation
- dependencies
- from source,
- distribution wise package manager
2) Development
- intended for developers
3) Troubleshooting
- Place to look for when things don't go as expected.

Wiki may not be the first place to have these sort of information but we
can always keep adding contents to it.

Thanks,

On Mon, Mar 14, 2016 at 3:15 PM, Shalil Awaley <notifications@github.com>
wrote:

> I think the current read me is not bad. If wiki is to be added, i dont
> know how it can be good.
> My analysis is the following topics
>
> Setting up
> Dependencies
> Install
> -Arch
> -Ubuntu
> -Building deb
> -Manual
> HOW-TO USE
>
> are required in Readme.
> Except these there is only a few to be removed.
>
> Since, the content is so little, i believe, either we should wait for the
> readme to increase, or we should add more contents in wiki to separate
> articles from read me and wiki.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/foss-np/batti/issues/33#issuecomment-196223883>.
>



-- 
With best regards,
Samundra Shrestha
http://www.samundra.com.np
Mobile: +977-9851236069

**Comment by rhoit** [comment]
I have restructured the **README**, and please blank sections, for respected os you use, 
@samundra add the Troubleshooting.

**Comment by krazedkrish** [comment]
Samundra's suggestion sounds good.
:+1:

I vote for " Let's start with it."
:)

And we can also discuss what topics to leave in the read me.

**Comment by krazedkrish** [comment]
Mobile interface ma comment thich na khojda close vayechaa sorry guys.

**Comment by rhoit** [comment]
@samundra there has been lots of changes, if it address your problem, please close the issue.

**Comment by samundra** [comment]
@rhoit I will go through them tonight and hopefully I can close it. :+1:  @krazedkrish

**Comment by samundra** [comment]
Project abandoned. Closing the thread.
