### ISSUE TITLE
Installation error from the latest commit

### ISSUE THREAD

**Issue by samundra** [foss-np/batti#34]
*Replication Steps:*

1. sudo git clone https://github.com/foss-np/batti --recursive
   - no issues, works good.

2. ./configure
   - no issues, works good

3. sudo make
   - throws following error

  ```
rm -f /usr/local/bin/batti
rm -rf /opt/batti
mkdir -p /opt/batti
install -m 755  main.py -t /opt/batti/
install: cannot stat ‘main.py’: No such file or directory
make: *** [install] Error 1
```

looks like the folder is being deleted before the installation of the application. I remember it worked last time.

System Details:
OS: Ubuntu 14.04 LTS
installation directory: /opt/

Let me know if you have any queries.

Thanks,
Samundra

**Comment by rhoit** [comment]
I couldn't recreate the problem, but should work fine with more new changes.

**Comment by zerOnepal** [comment]
Neither could I :camel:
http://showterm.io/39049e8717d0c69d83287#fast

**Comment by samundra** [comment]
Sorry for being late, I was in place with very limited internet connection. :)

Regarding the issue, it seems to happen if the installation directory is other than home directory. The installation worked fine in home directory but reports error in **/opt/** directory. 

Replication Steps:
- Clone the repository in **/opt/batti** directory
- Try **sudo make install** : It should throw error

**Note:** I haven't tested it for other directories.

**Comment by zerOnepal** [comment]
lol, my opt is public... :laughing:

**Comment by samundra** [comment]
@zerOnepal My opt is owned by root. I also tried **777** permission on batti folder only inside the **/opt/** directory. I don't want to set 777 on **/opt/** directory.

**Comment by rhoit** [comment]
@samundra its seems, like you are trying to clone in the place where its suppose to be installed in thats `/opt`.

the **install** script cleans the old existing files. and tries to copy the new one, here when you try to install it you are removing the file first, then tries to **copy**. :joy_cat: that's why its the problem.

if you directly clone to `/opt` try using `make link`

**Comment by rhoit** [comment]
@samundra are you still facing the problem?

**Comment by samundra** [comment]
I haven't tried it yet. Since I now know what exactly is happening during `make` I think I will be able to resolve it on my own. I hope it won't happen with your latest changes in the repo. I will try to do a fresh installation tonight and let you know. :8ball: currently stucked with urgent work :hourglass_flowing_sand:

**Comment by masterpradipg** [comment]
E: Malformed entry 49 in list file /etc/apt/sources.list (Suite)
E: The list of sources could not be read.

the error line is:
deb http://foss-np.github.io/deb-packages


this issue is in my ubuntu 16.04 ? 
Any solution??

**Comment by rhoit** [comment]
@masterpradipg this is the different issue can you post new issue.. 
i my best guess is there is no deb-packages.

**Comment by samundra** [comment]
@masterpradipg Though I haven't tried it yet. 

Did you already test it?

```bash
$ mkdir -p deb/DEBIAN
$ mkdir -p deb/usr/local/bin
$ cp main.sh deb/usr/local/bin/batti
$ cp info deb/DEBIAN/control
$ dpkg-deb --build deb .
```

These is supposed to create` .deb` package for the batti. You can also find above commands in `Makefile`.

@rhoit Lets work on packaging the repos into `.deb`

**Comment by rhoit** [comment]
I'm not in debian based system @samundra

**Comment by samundra** [comment]
How about arch packages :smiling_imp:  just kidding. I will look into packaging the repos someday :hourglass_flowing_sand:  There are few repos I am thinking to package. :wrench: 

- Anubad
- Loadshedding Unity indicator
- Batti

I will create separate discussion thread for these. :do_not_litter: 

Lets close this issue now we do not need it anymore.

:+1: :white_check_mark: issues resolved
