### ISSUE TITLE
conky.sh missing from master branch

### ISSUE THREAD

**Issue by samundra** [foss-np/batti#35]
Just a quick note, I saw that `conky.sh` is missing from the `master` branch and is available only in `print_usuage` branch. Was this intentional. 

I tried generating the conky configuration with `conky.sh` and found that it appends to my `.conkyrc` and reinitiates the conky. I think we'll have to change this default behaviour. We can just generate the conky configuration and leave it upto user whether he wants to use it or drop it. :)

I will go through the repo once today and follow up on it. :clock1030:

**Comment by rhoit** [comment]
i did remove it from the `master`. and and put it as the readme as instruction, `print_usage` is the branch of @zerOnepal
